### ISSUE TITLE
Multicolumn listbox(Treeview) not work with tkCalendar

### ISSUE THREAD

**Issue by aasadi1978** [j4321/tkcalendar#35]
I saw the same issue already posted on "[Problem with ttk.Treeview and calendar #9](https://github.com/j4321/tkcalendar/issues/9)"  but now I am using Python 3.6 on windows 10 and having the same issue. When use "pip install tkcalendar" it says all requirements satisfied. So it seems like updating tkCalendar will not help :(. Any advice please?

**Comment by j4321** [comment]
I have tested the code from the #9 with tkcalendar 1.4.0 in Windows 10 (but with python 3.7) and the window does not change size. The command to update tkcalendar with pip is 
`
pip install -U tkcalendar
`
otherwise it will just say "requirements already satisfied" so please check  whether your version of tkcalendar is 1.4.0. If you still have the same issue after that, I will try to reproduce it with python 3.6.

**Comment by aasadi1978** [comment]
Thanks Juliette. I tried with Python 3.7.1 and the problem still persists, unfortunately.   I also tried pip install -U tkcalendar and got the same response (as expected because i already have the latest version of tkcalendar). It is interesting because calendar is sitting on the parent windows and the Multicolumn Listbox (Treeview) generated on the TopLevel window, keeps expanding!!.

**Comment by j4321** [comment]
@aasadi1978, @dancushing Could either of you post the code that triggers the issue so that I can try to reproduce it? Does the code posted by Ivan88k in #9 still make your window expand?

**Comment by aasadi1978** [comment]
Hi Juliette. No, in my case it does not expand!

**Comment by aasadi1978** [comment]
I actually downloaded Multicolum-Listbox from the following link:

http://code.activestate.com/recipes/580794-simple-multicolumn-listbox-for-tkinter/

and plugged in my own code. Do you think the code in the link might have a bug?!

**Comment by j4321** [comment]
@aasadi1978 I think that the combination of the code in the link with tkcalendar is somehow creating the bug and since another user is experiencing the same issue, this is probably due to tkcalendar. But as long as I haven't identified exactly what triggers the issue I can't fix it. If you could give me a minimal example that reproduces the issue, it would really help me find out what's wrong with my code.

**Comment by aasadi1978** [comment]
Hi Juliette. Sorry for the delayed response. I actually used tk.Treeview to build my Multicolumn Listbox and the problem is gone. Thanks for following up and support.

**Comment by dawidciolek** [comment]
Hi aasadi1978, can you write more precisely what you changed in the code? I have this problem all the time ...

**Comment by aasadi1978** [comment]
Hi

It has been a very long time but I tried to remember. As mentioned in the
comment, I used Treeview to build the multi-column.
I think you have to store MultColumnList.py in the directory and load from
there. I attached it for your reference.
Hope it helps.
