### ISSUE TITLE
Calendar cursor in DateEntry bug

### ISSUE THREAD

**Issue by Tech-GS** [j4321/tkcalendar#55]
When determining your calendar cursor, for example, cursor = 'hand1', the cursor of the opened calendar does not change.
The problem was fixed as follows:

```python
class DateEntry(ttk.Entry):
    ...

    def __init__(self, master=None, **kw):
        ...
        for key in self.entry_kw:
            if not key in ['cursor']:
                entry_kw[key] = kw.pop(key, self.entry_kw[key])
        ...

```

**Comment by j4321** [comment]
With my implementation, only the cursor of the entry can be changed and I agree that it would be an improvement if the cursor on the calendar could be changed since it is possible with the `Calendar` widget. But with your solution, the cursor on the entry can no longer be set, only the one on the calendar.

Using the same cursor on both is not the right solution because usually one wants an 'insert' cursor on the entry and an 'arrow' on the calendar. So, I will think about giving different names to both options.
